IPC bridge
djunicode/ergo pull request #33
Opened 2021-04-26 08:39 UTC by ADIthaker

## Description

This pull request consists of all the required `ipc` for v1. The functions that are covered are `openTerm`, `launchEditor`, `launchFileManager`, `createProject`.

## Changes

`events` folder

## Issue

> Closes #29

## Impacted Area

> Entire project

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- uncomment code from `/app/src/pages/ProjectInfo/Action.js` into any buttons onClick event
- `npm run dev`

2021-04-26 14:32 UTC, namandangi approved these changes

2021-04-26 14:32 UTC, namandangi commented on app/src/pages/ProjectInfo/Action.js
> +                  preferredEdittor: "VSCode",
why is this whole chunk of code commented ??

2021-04-28 09:34 UTC, YJDoc2 requested changes

2021-04-28 09:34 UTC, YJDoc2 commented on app/electron/events/index.js
> +    // }
Remove the comments if not required

2021-04-28 13:51 UTC, YJDoc2 approved these changes

2021-04-28 13:52 UTC, merged